### ISSUE TITLE
AsharaStudios / ATforA9G english at command problem

### ISSUE THREAD

**Issue by majidmp97** [AsharaStudios/ATforA9G#3]
hi thank you abote update- but that at command just for gsm
how about gps english at command

**Comment by AlexFBP** [comment]
The most complete version of the AT commands (and the one we mostly used to build this library) is the 1.1, that are including the GPS AT Commands. "Unfortunately" the v1.1 is currently only in Chinese. The English version is currently the 1.0 so it is missing almost the half of the commands within v1.1

("Unfortunately" = we don't -yet- speak Chinese, so we just scanned the v1.1 Chinese AT specification (opened in a PC) with the Camera from the Google Translate app in Android)

**Comment by majidmp97** [comment]
that's funny-in year 2020 with last and great technology-  the one of the begiset iot maker company don't have english document for engineer

**Comment by AlexFBP** [comment]
Related to #2
