### ISSUE TITLE
ATforA9G library

### ISSUE THREAD

**Issue by Achimi-Dennis** [AsharaStudios/ATforA9G#4]
please, can you upload the Driver Library for Ai-Thinker's A9G and their packages to PlatformIO manually?

**Comment by AlexFBP** [comment]
Hi @Achimi-Dennis , sorry for the delay

Can you please clarify? I mean, we don't connect directly to the A9G but through serial port, and if you use PlatformIO, you can simply use this library by modifying your .ini, as mentioned in the readme...

**Comment by AlexFBP** [comment]
Closing by inactivity. Please don't open a new Issue, reopen this if required @Achimi-Dennis
